name: Update rules.minify.hash

on:
  push:
    branches: [ main ]
    paths:
      - 'data.minify.json'
      - '.github/workflows/update-rules-hash.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute SHA256 and write file
        run: |
          set -euo pipefail
          test -f data.minify.json
          hash=$(sha256sum data.minify.json | awk '{print $1}')
          printf "%s\n" "$hash" > rules.minify.hash
          echo "SHA256: $hash"

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rules.minify.hash
          git commit --allow-empty -m "chore(ci): update rules.minify.hash [skip ci]"
          git push
